name: Deploy to Cloudflare Pages

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ubiquity/.github/.github/workflows/deploy.yml@main
    with:
      production_branch: main
    permissions:
      contents: read
      pull-requests: write
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      UBIQUITY_BOUNTY_BOT_APP_ID: ${{ secrets.APP_ID }}
      UBIQUITY_BOUNTY_BOT_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
